### ISSUE TITLE
Should get(undefined) return an undefined?

### ISSUE THREAD

**Issue by emilis** [GraphOrigami/origami#1]
https://github.com/GraphOrigami/origami/blob/5df76cfccb19ff244883ff42fa9f4be9c0617c0d/packages/core/src/ObjectDictionary.js#L24-L28

Are you sure this is a good idea?

Consider how Maps work:

```javascript
> m = new Map
Map(0) {}
> m.get()
undefined
> m.get(undefined)
undefined
```

Also what if someone does this:

```javascript
getByPath(
    aGraph,
    [ request.params.company, request.params.prodict, 'data.json', 'link' ],
)
```

There is a typo. It would be better for the code to fail (by returning an undefined) instead of returning the wrong link.

**Comment by JanMiksovsky** [comment]
While I won’t have time to address this for a while, I wanted to at least write down some thoughts. I should begin by explaining why this code exists.

I am trying to design the different levels of Graph Origami such that the low-level foundation supports desirable behavior in the higher levels like the CLI and framework.

In this case, I would like the CLI and framework to handle some common aspects of file system path behavior and HTTP URLs.

* File system paths generally ignore successive slashes: `foo/bar` and `foo///bar` are equivalent.
* This is sometimes (but not always) the case in URLs as well.
* A file system path for a directory treats a trailing slash as optional: `foo` and `foo/` are equivalent.
* This is sometimes (but not always) the case for URLs for areas containing subpages. If a site has a `foo` area that contains resources like `foo/bar.html`, then the users can often reference the `foo` area itself as either `foo` or `foo/`. The site may redirect one form to the other, or may simply return the same resource for either path.

I’d like the CLI and framework to support such behavior in traversing graphs. Graph Origami could bake these rules into helper functions like `traverse`, but that would force developers to remember these rules any time they are implementing their own graph traversal code.

Since I think writing traversal code is more common that creating new graph drivers, my solution for some time has been to split responsibility for such rules into two places:

First: The language parser turns a path like `foo/bar/baz` into an operation like `traverse("foo", "bar", "baz")`. The parser treats successive slashes like `//` as if the missing path key were `undefined`. So `foo//bar` becomes `traverse("foo", undefined, "bar")`.

Second: The `get` function in reference graph drivers like `ObjectGraph` and `FilesGraph` defines `get(undefined)` to return the graph itself.

This combination produces support for the file system path and URL behavior described above.

However, your question is now forcing me to reconsider the specifics of this solution. I have indeed hit cases where a traverse argument evaluated to `undefined`, and can take a while to diagnose the root of the problem.

A similar but perhaps less risky solution might be to treat a missing path key as the empty string `""` instead of `undefined`:

* `foo//bar` → `traverse("foo", "", "bar")`
* `foo/` → `traverse("foo", "")`

**Comment by JanMiksovsky** [comment]
The core graphs have been rewritten to use a special `defaultValueKey` symbol instead of `undefined` to handle the path behavior described above:
* `foo/bar` → `traverse("foo", "bar")`
* `foo/bar/` → `traverse("foo", "bar", defaultValueKey)`
A graph can opt into supporting this default value behavior by importing the `defaultValueKey` symbol and testing for it in the `get()` method. Graphs don't have to support that behavior, so if a dev doesn't want to handle it they can ignore it.

This avoids the potential for issues using `undefined` for that purpose. While the implemented solution may shift again in the future, I think the original issue has been addressed.
